<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Питання відповідь</title>
    <!-- Шрифты с Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

    <!-- Стили сайта -->
    <link rel="stylesheet" href="../static/style.css">
</head>
<body>
<header>
    <a href="/fscreen" class="navbar-brand">Calorie Tracker</a>

    <nav>
        <ul>
            <li><a href="/calorie">Calorie Calculator</a></li>
            <li><a href="#">button2</a></li>
            <li><a href="#">Contacts &Congruent;</a>
                <ul>
                    <li><a href=mailto: denusveluchko2017@gmail.com>Gmail</a></li>
                    <li><a href="https://github.com/Shushpin/Velychko.LvivUniversity.PersonalProject">GitHub</a></li>
                    <li><a href="#">Social networks =</a>
                        <ul>
                            <li><a href="https://www.instagram.com/velychko_d">Instagram</a></li>
                            <li><a href="https://t.me/gamabunta429">Telegram</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="/fscreen">FAQs</a></li>
            <li><a href="/login">Log out</a></li>
        </ul>
    </nav>
</header>
<section>
    <h2 class="title">The most interesting questions</h2>

    <div class="faq">
        <div class="question">
            <h3>What is a calorie tracker and how does it help me monitor my diet and overall health?</h3>

            <svg widht="15" height="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3" stroke="white" stroke-widht="7" stroke-linecap="round"/>
            </svg>
        </div>
        <div class="answer">
            <p>
                A calorie tracker is a tool that helps you monitor and record the number of calories you consume each day.
                It can also track other nutrients such as protein, fat, and carbohydrates. By using a calorie tracker, you can keep track of your diet and maintain a healthy weight.
            </p>
        </div>
    </div>

    <div class="faq">
        <div class="question">
            <h3>What kind of data can I track with a calorie tracker and how does it help me control my food intake??</h3>

            <svg widht="15" height="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3" stroke="white" stroke-widht="7" stroke-linecap="round"/>
            </svg>
        </div>
        <div class="answer">
            <p>
                With a calorie tracker, you can track the number of calories you consume in each meal or snack. This helps you control your food intake and stay within a certain calorie range. Some calorie trackers also allow you to track other nutrients like protein, fat, and carbohydrates.
            </p>
        </div>
    </div>

    <div class="faq">
        <div class="question">
            <h3>What data do I need to input into a calorie tracker to get the most accurate results?</h3>

            <svg widht="15" height="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3" stroke="white" stroke-widht="7" stroke-linecap="round"/>
            </svg>
        </div>
        <div class="answer">
            <p>
                To get the most accurate results from a calorie tracker, you need to input information about the food you eat and the quantity you consume. This includes information like the type of food, portion size, and the time you consumed it.
            </p>
        </div>
    </div>

    <div class="faq">
        <div class="question">
            <h3>Can I use a calorie tracker to count calories consumed during exercise, and how does it work?</h3>

            <svg widht="15" height="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3" stroke="white" stroke-widht="7" stroke-linecap="round"/>
            </svg>
        </div>
        <div class="answer">
            <p>
                Yes, you can use a calorie tracker to count calories burned during exercise. Some calorie trackers have the ability to track your physical activity and estimate the number of calories burned based on your weight, age, and other factors.
            </p>
        </div>
    </div>

    <div class="faq">
        <div class="question">
            <h3>What features of a calorie tracker help improve the quality of my diet and achieve health and fitness goals?</h3>

            <svg widht="15" height="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3" stroke="white" stroke-widht="7" stroke-linecap="round"/>
            </svg>
        </div>
        <div class="answer">
            <p>
                Calorie trackers often have features that can help you achieve health and fitness goals. For example, some trackers provide recommendations for daily calorie intake based on your age, sex, height, and weight. Others allow you to set goals and track your progress towards them, such as losing weight or building muscle.
            </p>
        </div>
    </div>

</section>
<script src="/app.js"></script>
</body>
</html>