<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ГОЛОВНИЙ ЕКРАН</title>

    <!-- Шрифты с Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

    <!-- Стили сайта -->
    <link rel="stylesheet" type="text/css" href="../static/style.css">
</head>
<body>

<header>
    <a href="/fscreen" class="navbar-brand">Calorie Tracker</a>

    <nav>
        <ul>
            <li><a href="/calorie">Calorie Calculator</a></li>
            <li><a href="#">button2</a></li>
            <li><a href="#">Contacts &Congruent;</a>
                <ul>
                    <li><a href=mailto: denusveluchko2017@gmail.com>Gmail</a></li>
                    <li><a href="https://github.com/Shushpin/Velychko.LvivUniversity.PersonalProject">GitHub</a></li>
                    <li><a href="#">Social networks =</a>
                        <ul>
                            <li><a href="https://www.instagram.com/velychko_d">Instagram</a></li>
                            <li><a href="https://t.me/gamabunta429">Telegram</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="/faq">FAQs</a></li>
            <li><a href="/login">Log out</a></li>
        </ul>
    </nav>
</header>

</body>
</html>