<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../static/style.css">
    <title>Form Registration</title>
</head>
<body>
<main>
    <div class="circle"></div>
    <div class="register-form-container">
        <h1 class="form-title">
            Registration
        </h1>
        <div class="form-fields">
            <div class="form-field">
                <input type="text" placeholder="Name">
            </div>
            <div class="form-field">
                <input type="text" placeholder="Email">
            </div>
            <div class="form-field">
                <input type="password" placeholder="Password">
            </div>
            <div class="form-field">
                <input type="password" placeholder="Confirm Password">
            </div>
        </div>
        <div class="form-buttons">
            <a class="button" href="/login">Registration</a>
            <div class="divider">⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ or ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯</div>
            <a href="#" class="button button-google">Google</a>
        </div>
        <div class="login-field">
            <p>Already have an account? <a href="/login">Log in</a></p>
        </div>
    </div>
</main>
</body>
</html>