<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../static/style.css">
    <title>Form Login</title>
</head>
<body>
<main>
    <div class="circle"></div>
    <div class="login-form-container">
        <h1 class="form-title">
            Log In
        </h1>
        <div class="form-fields">
            <div class="form-field">
                <input type="text" placeholder="Email">
            </div>
            <div class="form-field">
                <input type="password" placeholder="Password">
            </div>
        </div>
        <div class="form-buttons">
            <a class="button" href="/fscreen">Sign in</a>
        </div>
        <div class="login-field">
            <p>Don't have an account yet? <a href="/index"> Create</a></p>
        </div>
    </div>
</main>
</body>
</html>